repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.0
    hooks:
      - id: ruff-check
        args:
          [
            "--fix",
            "--config",
            "lint.extend-ignore=['C901','PLR09']",  # complexity rules not enforced, informational only
          ]
      - id: ruff-format

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.12.0
    hooks:
      - id: uv-lock
